apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: {{ .Values.namespaceOverride }}
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccount: jenkins
      initContainers:
        - name: fix-permissions
          image: {{  .Values.images.initContainer.image }}:{{  .Values.images.initContainer.tag }}
          command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: jenkinshome
              mountPath: /var/jenkins_home
      containers:
        - name: jenkins
          image: {{  .Values.images.jenkins.image }}:{{  .Values.images.jenkins.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: -Dhudson.model.DownloadService.noSignatureCheck=true
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
            - containerPort: 50000
              name: agent
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 12
          volumeMounts:
            - name: jenkinshome
              mountPath: /var/jenkins_home
            - mountPath: /var/run/docker.sock
              name: dockersock
            - mountPath: /usr/bin/docker
              name: docker
      volumes:
        - name: jenkinshome
          hostPath:
            path: /root/jenkins-data
            type: Directory
        - name: dockersock
          hostPath:
            # 宿主上目录位置
            path: /var/run/docker.sock
            type: Socket
        - name: docker
          hostPath:
            # 宿主上目录位置
            path: /usr/bin/docker
          # 此字段为可选