apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: {{ .Values.namespaceOverride }}
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - name: web
      port: 8080
      targetPort: web
    - name: agent
      port: 50000
      targetPort: agent